# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: devclean

before:
  hooks:
    - go mod tidy

builds:
  - id: devclean
    binary: devclean
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
checksum:
  disable: true # name_template: checksums.txt

brews:
  - name: devclean
    description: "macOS-oriented developer environment cleanup tool"
    homepage: "https://github.com/wangweicheng7/devclean"
    license: "MIT"
    install: |
      bin.install "devclean"
    repository:
      owner: wangweicheng7
      name: homebrew-tap
      branch: main

    commit_author:
      name: goreleaserbot
      email: goreleaser@users.noreply.github.com


