# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 2

project_name: devclean

before:
  hooks:
    - go mod tidy

builds:
  - id: devclean
    main: .
    binary: devclean
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: >
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}
checksum:
  name_template: checksums.txt

brews:
  - name: devclean
    homepage: https://github.com/wangweicheng7/devclean
    description: Developer environment cleaner for macOS / Linux
    license: MIT
    repository:
      owner: wangweicheng7
      name: homebrew-tap
    install: |
      bin.install "devclean"

